name = "ravan-yar"
main = "src/worker.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ravan-yar-db"
database_id = "b9b8f05e-d8c4-4e9c-8281-50c8199938fa"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "ravan-yar-media"
